CREATE TABLE "receipt_settings" (
	"id" serial PRIMARY KEY NOT NULL,
	"paper_width" text DEFAULT '58mm' NOT NULL,
	"paper_padding" text DEFAULT '3mm 4mm 8mm' NOT NULL,
	"font_family" text DEFAULT '''IBM Plex Mono'', ''Courier New'', monospace' NOT NULL,
	"font_import_url" text DEFAULT 'https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600;700&display=swap' NOT NULL,
	"base_font_size_px" integer DEFAULT 9 NOT NULL,
	"shop_name" text DEFAULT 'Akiro Laundry' NOT NULL,
	"shop_tagline" text DEFAULT 'Premium Laundry & Perfume Service' NOT NULL,
	"logo_url" text DEFAULT '' NOT NULL,
	"logo_alt" text DEFAULT 'Akiro Laundry' NOT NULL,
	"logo_max_height" text DEFAULT '32px' NOT NULL,
	"accent_color" text DEFAULT '#0f5a85' NOT NULL,
	"accent_bg_color" text DEFAULT '#f0f7fd' NOT NULL,
	"accent_border_color" text DEFAULT '#b6def5' NOT NULL,
	"meta_label_color" text DEFAULT '#607080' NOT NULL,
	"notes_bg_color" text DEFAULT '#fffbeb' NOT NULL,
	"notes_border_color" text DEFAULT '#fcd34d' NOT NULL,
	"notes_accent_color" text DEFAULT '#f59e0b' NOT NULL,
	"notes_text_color" text DEFAULT '#78350f' NOT NULL,
	"change_color" text DEFAULT '#15803d' NOT NULL,
	"unpaid_color" text DEFAULT '#d97706' NOT NULL,
	"show_logo" boolean DEFAULT false NOT NULL,
	"show_shop_name" boolean DEFAULT true NOT NULL,
	"show_tagline" boolean DEFAULT true NOT NULL,
	"show_order_number" boolean DEFAULT true NOT NULL,
	"show_customer_address" boolean DEFAULT true NOT NULL,
	"show_payment_method" boolean DEFAULT true NOT NULL,
	"show_amount_paid" boolean DEFAULT true NOT NULL,
	"show_change_given" boolean DEFAULT true NOT NULL,
	"show_notes" boolean DEFAULT true NOT NULL,
	"show_footer" boolean DEFAULT true NOT NULL,
	"footer_thank_you" text DEFAULT 'Thank you for choosing {{shopName}}!' NOT NULL,
	"footer_contact" text DEFAULT '📞 +670 7675 8 7380  ·  akirolaundry.com' NOT NULL,
	"print_delay_ms" integer DEFAULT 600 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
